# MANAGED FILE: to push changes see buildcheck/README.md - template: buildcheck/data/templates/handler/riff-raff.yaml.ts
stacks:
  - support
regions:
  - eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  imovo-voucher-api-cloudformation:
    type: cloud-formation
    app: imovo-voucher-api
    parameters:
      templateStagePaths:
        CODE: imovo-voucher-api-CODE.template.json
        PROD: imovo-voucher-api-PROD.template.json
  imovo-voucher-api:
    type: aws-lambda
    parameters:
      fileName: imovo-voucher-api.zip
      bucketSsmLookup: true
      prefixStack: false
      functionNames:
        - imovo-voucher-api-
    dependencies:
      - imovo-voucher-api-cloudformation
